/* PLATAFORMA CLIENTES — núcleo seguro V1 */
(()=>{
'use strict';
const DB='PLATAFORMA_CLIENTES_DB', VER=1;
const stores=['companies','folders','documents','norms','audit'];
let db, companyId=null, folderId=null, subfolderId=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString();
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result; for(const s of stores){if(!d.objectStoreNames.contains(s)){const o=d.createObjectStore(s,{keyPath:'id'}); if(s==='documents'||s==='folders'||s==='norms')o.createIndex('companyId','companyId');}}};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function getAll(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function audit(action,entity,entityId,detail=''){await put('audit',{id:crypto.randomUUID(),at:now(),user:sessionStorage.user||'gladys',action,entity,entityId,detail})}
async function seed(){let cs=await getAll('companies');if(!cs.length){await put('companies',{id:'wonder',name:'WONDER PACK S.A.S.',nit:'',city:'Medellín',employees:30,risk:'IV',arl:'ARL SURA',createdAt:now(),updatedAt:now()});for(const [i,n] of [['01','ORGANIZACIÓN'],['02','PLANIFICACIÓN'],['03','APLICACIÓN'],['04','VERIFICACIÓN'],['05','MEJORAMIENTO'],['06','POLÍTICAS']])await put('folders',{id:'wonder-'+i,companyId:'wonder',parentId:null,code:i,name:n,kind:'root',createdAt:now()});}
// Importación de datos antiguos si existen y aún no se ha hecho.
const migrated=localStorage.getItem('pc_migrated_v1');if(!migrated){for(const k of ['pc_v8','pc_v7','pc_v6','pc_v5']){try{const old=JSON.parse(localStorage.getItem(k)||'null');if(old?.companies?.length){for(const c of old.companies){if(!(await getAll('companies')).some(x=>x.id===c.id))await put('companies',{...c,createdAt:c.createdAt||now(),updatedAt:now()});}for(const d of old.docs||[]){await put('documents',{...d,id:String(d.id||crypto.randomUUID()),createdAt:d.created||now(),updatedAt:now()});}break}}catch(e){}}localStorage.setItem('pc_migrated_v1',now());await audit('MIGRACIÓN','sistema','v1','Datos locales importados cuando estaban disponibles');}}
async function render(){const cs=await getAll('companies');if(!companyId||!cs.some(c=>c.id===companyId))companyId=cs[0]?.id;const c=cs.find(x=>x.id===companyId);const fs=(await getAll('folders')).filter(x=>x.companyId===companyId);const docs=await getAll('documents');$('#company').innerHTML=cs.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');$('#company').value=companyId||'';const roots=fs.filter(x=>!x.parentId);$('#nav').innerHTML=roots.map(r=>{const subs=fs.filter(x=>x.parentId===r.id);return `<div class="navgroup"><button class="navitem ${folderId===r.id?'sel':''}" data-folder="${r.id}">${r.code} · ${esc(r.name)} <b>${docs.filter(d=>d.companyId===companyId&&d.folderId===r.id).length}</b></button>${folderId===r.id?`<button class="newsub" id="newsub">＋ Nueva subcarpeta</button>${subs.map(s=>`<button class="subitem ${subfolderId===s.id?'sel':''}" data-sub="${s.id}">📁 ${esc(s.name)} <b>${docs.filter(d=>d.subfolderId===s.id).length}</b></button>`).join('')}`:''}</div>`}).join('');$('#content').innerHTML=page(c,roots,fs,docs);}
function page(c,roots,fs,docs){const f=fs.find(x=>x.id===folderId),s=fs.find(x=>x.id===subfolderId),list=docs.filter(d=>d.companyId===companyId&&(!folderId||d.folderId===folderId)&&(!subfolderId||d.subfolderId===subfolderId));return `<div class="hero"><div><small>PLATAFORMA CLIENTES / ${esc(f?.name||'INICIO')}</small><h1>${esc(c?.name||'Sin empresa')}</h1><p>${esc(c?.city||'Ciudad')} · ${c?.employees||0} trabajadores · Riesgo ${esc(c?.risk||'—')} · ${esc(c?.arl||'—')}</p></div><div><button class="btn" id="newdoc">＋ Documento</button><button class="btn primary" id="ai">✦ IA</button></div></div><div class="stats"><div><small>EMPRESAS</small><strong>${roots.length?new Set(fs.map(x=>x.companyId)).size:0}</strong></div><div><small>CARPETAS</small><strong>6</strong></div><div><small>SUBCARPETAS</small><strong>${fs.filter(x=>x.parentId).length}</strong></div><div><small>DOCUMENTOS</small><strong>${docs.filter(d=>d.companyId===companyId).length}</strong></div></div><section class="panel"><header><div><h2>${esc(s?.name||f?.name||'Expediente')}</h2><p>Los documentos quedan asociados a empresa, carpeta y subcarpeta.</p></div></header><table><thead><tr><th>CÓDIGO</th><th>DOCUMENTO</th><th>TIPO</th><th>VERSIÓN</th><th>ESTADO</th></tr></thead><tbody>${list.length?list.map(d=>`<tr><td>${esc(d.code||'—')}</td><td>${esc(d.name)}</td><td>${esc(d.type||'—')}</td><td>${esc(d.version||'01')}</td><td>${esc(d.status||'BORRADOR')}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">No hay documentos en esta ubicación.</td></tr>`}</tbody></table></section><section class="panel"><header><h2>CONTROL DEL SISTEMA</h2><p>Respaldo, restauración y biblioteca normativa.</p></header><div class="cards"><button class="cardbtn" id="backup">💾 Descargar respaldo completo</button><button class="cardbtn" id="restore">↩ Restaurar respaldo</button><button class="cardbtn" id="norms">⚖ Biblioteca normativa</button></div></section>`}
function modal(title,body){let m=$('#modal');m.innerHTML=`<div class="modalbox"><h2>${title}</h2>${body}<div class="right"><button class="btn" id="close">Cerrar</button></div></div>`;m.style.display='grid';$('#close').onclick=()=>m.style.display='none'}
async function newCompany(){modal('Nueva empresa',`<input id="nname" placeholder="Razón social"><input id="nnit" placeholder="NIT"><input id="ncity" placeholder="Ciudad"><input id="nemp" type="number" placeholder="Trabajadores"><select id="nrisk"><option>I</option><option>II</option><option>III</option><option>IV</option><option>V</option></select><input id="narl" placeholder="ARL"><div class="right"><button class="btn primary" id="savec">Crear empresa</button></div>`);$('#savec').onclick=async()=>{const name=$('#nname').value.trim();if(!name)return alert('Escribe la razón social.');const id=crypto.randomUUID();await put('companies',{id,name,nit:$('#nnit').value.trim(),city:$('#ncity').value.trim(),employees:Number($('#nemp').value)||0,risk:$('#nrisk').value,arl:$('#narl').value.trim(),createdAt:now(),updatedAt:now()});for(const [code,n] of [['01','ORGANIZACIÓN'],['02','PLANIFICACIÓN'],['03','APLICACIÓN'],['04','VERIFICACIÓN'],['05','MEJORAMIENTO'],['06','POLÍTICAS']])await put('folders',{id:id+'-'+code,companyId:id,parentId:null,code,name:n,kind:'root',createdAt:now()});companyId=id;folderId=id+'-01';subfolderId=null;await audit('CREAR','empresa',id,name);$('#modal').style.display='none';await render()}}
async function newSub(){const fs=await getAll('folders');const f=fs.find(x=>x.id===folderId);modal('Nueva subcarpeta',`<p>Dentro de <b>${esc(f?.name||'carpeta')}</b></p><input id="sn" placeholder="Nombre de la subcarpeta"><input id="sc" placeholder="Código (opcional)"><div class="right"><button class="btn primary" id="saves">Crear</button></div>`);$('#saves').onclick=async()=>{const name=$('#sn').value.trim();if(!name)return alert('Escribe el nombre.');const id=crypto.randomUUID();await put('folders',{id,companyId,parentId:folderId,code:$('#sc').value.trim(),name,kind:'sub',createdAt:now()});subfolderId=id;await audit('CREAR','subcarpeta',id,name);$('#modal').style.display='none';await render()}}
async function newDoc(){const fs=await getAll('folders'),f=fs.find(x=>x.id===folderId),s=fs.find(x=>x.id===subfolderId);modal('Nuevo documento',`<p><b>${esc(f?.name||'')}</b> ${s?' / '+esc(s.name):''}</p><input id="dc" placeholder="Código"><input id="dn" placeholder="Nombre del documento"><select id="dt"><option>Procedimiento</option><option>Programa</option><option>Plan</option><option>Política</option><option>Formato</option><option>Acta</option><option>Informe</option><option>Matriz</option><option>Manual</option></select><textarea id="do" placeholder="Descripción / requisitos"></textarea><div class="right"><button class="btn primary" id="saved">Guardar</button></div>`);$('#saved').onclick=async()=>{const name=$('#dn').value.trim();if(!name)return alert('Escribe el nombre.');const id=crypto.randomUUID();await put('documents',{id,companyId,folderId,subfolderId:subfolderId||null,code:$('#dc').value.trim(),name,type:$('#dt').value,version:'01',status:'BORRADOR',description:$('#do').value,createdAt:now(),updatedAt:now()});await audit('CREAR','documento',id,name);$('#modal').style.display='none';await render()}}
async function norms(){const ns=await getAll('norms');modal('Biblioteca normativa',`<p>Repositorio preparado para normas por sistema, vigencia y aplicabilidad.</p><input id="nq" placeholder="Buscar norma"><div id="nlist">${ns.length?ns.map(n=>`<div class="norm"><b>${esc(n.code)}</b> · ${esc(n.title)}<br><small>${esc(n.topic||'')} · ${esc(n.status||'Vigente')}</small></div>`).join(''):'<div class="empty">La biblioteca está lista para cargar la matriz normativa vigente.</div>'}</div>`)}
async function backup(){const data={format:'PC-BACKUP-1',createdAt:now(),companies:await getAll('companies'),folders:await getAll('folders'),documents:await getAll('documents'),norms:await getAll('norms'),audit:await getAll('audit')};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='PLATAFORMA_CLIENTES_RESPALDO_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);await audit('RESPALDO','sistema','backup')}
function restore(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{const f=i.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.format!=='PC-BACKUP-1')throw Error('Formato inválido');for(const s of stores){for(const x of d[s]||[])await put(s,x)}alert('Respaldo restaurado correctamente.');await render()}catch(e){alert('No se pudo restaurar el respaldo: '+e.message)}};i.click()}
async function ai(){modal('Asistente IA',`<p>Preparador documental por empresa y carpeta.</p><textarea id="aq" placeholder="Ej.: Crear procedimiento de inspecciones de seguridad con referencias normativas aplicables"></textarea><div class="right"><button class="btn primary" id="sendai">Preparar</button></div><div id="aiout"></div>`);$('#sendai').onclick=()=>{$('#aiout').innerHTML='<div class="result">Solicitud registrada. La conexión con el proveedor de IA debe configurarse en el servidor para generar documentos reales de forma segura.</div>'}}
async function boot(){await openDB();await seed();$('#login').innerHTML='<div class="loginbox"><div class="brand"><strong>PLATAFORMA CLIENTES</strong><small>Gestión integral empresarial</small></div><h1>Ingreso privado</h1><input id="lu" placeholder="Usuario"><input id="lp" type="password" placeholder="Contraseña"><button class="btn primary" id="loginbtn">Ingresar</button><p class="muted">Almacenamiento local seguro + respaldo exportable.</p></div>';$('#loginbtn').onclick=()=>{if($('#lu').value==='gladys'&&$('#lp').value==='GladysPro2026!'){sessionStorage.user='gladys';$('#login').style.display='none';$('#app').style.display='block';render()}else alert('Usuario o contraseña incorrectos.')};if(sessionStorage.user==='gladys'){ $('#login').style.display='none';$('#app').style.display='block';render()}}
window.addEventListener('click',async e=>{if(e.target.id==='newcompany')newCompany();if(e.target.dataset.folder){folderId=e.target.dataset.folder;subfolderId=null;render()}if(e.target.dataset.sub){subfolderId=e.target.dataset.sub;render()}if(e.target.id==='newsub')newSub();if(e.target.id==='newdoc')newDoc();if(e.target.id==='ai')ai();if(e.target.id==='backup')backup();if(e.target.id==='restore')restore();if(e.target.id==='norms')norms()});window.addEventListener('change',e=>{if(e.target.id==='company'){companyId=e.target.value;folderId=companyId+'-01';subfolderId=null;render()}});boot();
})();
