(()=>{'use strict';
const SB_URL='https://blonebsjvsborinfmyhg.supabase.co';
const SB_KEY='sb_publishable_RgvgvQDV9gnxZe-tin1vLA_i5P6jLVq';
const H={apikey:SB_KEY,Authorization:'Bearer '+SB_KEY};
const api=async(path,opts={})=>{const r=await fetch(SB_URL+'/rest/v1/'+path,{...opts,headers:{...H,'Content-Type':'application/json',...(opts.headers||{})}});const t=await r.text();if(!r.ok)throw new Error('Supabase '+r.status+': '+t);return t?JSON.parse(t):null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function context(){const company=document.querySelector('#company')?.value||'',system=document.querySelector('#system')?.value||'';const folder=document.querySelector('.navitem.sel')?.dataset.folder||document.querySelector('.navitem[data-folder]')?.dataset.folder||'';const sub=document.querySelector('.subitem.sel')?.dataset.sub||null;return{company,system,folder,sub}}
function refresh(){const s=document.querySelector('#system');if(s)s.dispatchEvent(new Event('change',{bubbles:true}))}
function filePicker(){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.multiple=true;i.onchange=()=>resolve([...i.files]);i.click()})}
async function uploadOwn(){const c=context();if(!c.company||!c.system||!c.folder)return alert('Selecciona una empresa, sistema y carpeta antes de subir.');const files=await filePicker();if(!files.length)return;for(const file of files){const id=crypto.randomUUID(),safe=file.name.replace(/[^\\w.\\- ]/g,'_'),path=c.company+'/'+c.system+'/'+id+'-'+safe;const r=await fetch(SB_URL+'/storage/v1/object/documentos-clientes/'+path,{method:'POST',headers:{...H,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok)throw new Error('No se pudo guardar '+file.name+': '+await r.text());await api('documents',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id,company_id:c.company,system_id:c.system,folder_id:c.folder,subfolder_id:c.sub||null,name:file.name,type:'ARCHIVO',version:'01',status:'CARGADO',description:'Archivo almacenado en documentos-clientes/'+path,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})})}refresh()}
async function createOwn(){const c=context();if(!c.company||!c.system||!c.folder)return alert('Selecciona una empresa, sistema y carpeta antes de crear.');const name=prompt('Nombre del documento:');if(!name?.trim())return;const types=['Procedimiento','Programa','Plan','Política','Formato','Acta','Informe','Matriz','Manual'];const n=prompt('Tipo de documento:\n'+types.map((x,i)=>(i+1)+'. '+x).join('\n'),'1'),idx=Math.max(0,Math.min(types.length-1,(parseInt(n||'1',10)||1)-1)),description=prompt('Descripción / requisitos (opcional):','')||'';await api('documents',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:crypto.randomUUID(),company_id:c.company,system_id:c.system,folder_id:c.folder,subfolder_id:c.sub||null,name:name.trim(),type:types[idx],version:'01',status:'BORRADOR',description,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})});refresh()}
async function paint(){try{const c=document.querySelector('#company')?.value,s=document.querySelector('#system')?.value;if(!c||!s)return;const docs=await api('documents?select=*&company_id=eq.'+encodeURIComponent(c)+'&system_id=eq.'+encodeURIComponent(s)+'&order=created_at.desc'),folder=document.querySelector('.navitem.sel')?.dataset.folder||document.querySelector('.navitem[data-folder]')?.dataset.folder,sub=document.querySelector('.subitem.sel')?.dataset.sub||'',visible=docs.filter(d=>d.folder_id===folder&&(!sub||d.subfolder_id===sub)),table=document.querySelector('#content table'),tbody=table?.querySelector('tbody');if(!tbody)return;tbody.innerHTML=visible.length?visible.map(d=>'<tr><td>'+esc(d.code||'ARCHIVO')+'</td><td>'+esc(d.name)+'</td><td>'+esc(d.type)+'</td><td>'+esc(d.version)+'</td><td>'+esc(d.status)+'</td><td><button class="btn" data-open-doc="'+esc(d.id)+'">Abrir</button></td></tr>').join(''):'<tr><td colspan="6" class="empty">No hay documentos aquí. Usa “Crear documento” o “Subir documento”.</td></tr>';const stat=document.querySelectorAll('.stats>div')[3]?.querySelector('strong');if(stat)stat.textContent=visible.length;document.querySelectorAll('.navitem').forEach(b=>{const x=b.querySelector('b');if(x)x.textContent=docs.filter(d=>d.folder_id===b.dataset.folder).length});document.querySelectorAll('.subitem').forEach(b=>{const x=b.querySelector('b');if(x)x.textContent=docs.filter(d=>d.subfolder_id===b.dataset.sub).length});table.querySelectorAll('[data-open-doc]').forEach(b=>b.onclick=async()=>{const d=docs.find(x=>x.id===b.dataset.openDoc);if(!d)return;const text=String(d.description||''),p='documentos-clientes/',i=text.indexOf(p);if(i<0)return alert('Este documento no tiene un archivo asociado.');const path=text.slice(i+p.length),r=await fetch(SB_URL+'/storage/v1/object/download/documentos-clientes/'+path,{headers:H});if(!r.ok)return alert('No se pudo abrir el archivo: '+await r.text());const u=URL.createObjectURL(await r.blob());window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)})}catch(e){console.warn('Visualización:',e)}}
document.addEventListener('click',e=>{const t=e.target.closest?.('#upload,#newdoc');if(!t)return;e.preventDefault();e.stopImmediatePropagation();(t.id==='upload'?uploadOwn():createOwn()).catch(err=>alert(err.message))},true);
window.addEventListener('load',()=>setTimeout(paint,1200));setInterval(paint,2500);
})();