(()=>{'use strict';
const SB_URL='https://blonebsjvsborinfmyhg.supabase.co';
const SB_KEY='sb_publishable_RgvgvQDV9gnxZe-tin1vLA_i5P6jLVq';
const headers={apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json'};
const api=async(path,opts={})=>{const r=await fetch(SB_URL+'/rest/v1/'+path,{...opts,headers:{...headers,...(opts.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t);return t?JSON.parse(t):null};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
async function syncLocalDocuments(){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('PC_LOCAL_V4');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(!db.objectStoreNames.contains('documents'))return;const rows=await new Promise((res,rej)=>{const r=db.transaction('documents').objectStore('documents').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});for(const d of rows||[]){try{await api('documents?select=id&id=eq.'+encodeURIComponent(d.id));const body={id:d.id,company_id:d.companyId,system_id:d.systemId,folder_id:d.folderId,subfolder_id:d.subfolderId||null,code:d.code||'',name:d.name,type:d.type||'ARCHIVO',version:d.version||'01',status:d.status||'BORRADOR',description:d.description||'',created_at:d.createdAt||new Date().toISOString(),updated_at:d.updatedAt||new Date().toISOString()};await api('documents',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)})}catch(e){console.warn('No se pudo sincronizar documento local',d?.name,e)}}}catch(e){console.warn('Sincronización local omitida',e)}}
async function paintDocuments(){try{const company=document.querySelector('#company')?.value,system=document.querySelector('#system')?.value;if(!company||!system)return;const docs=await api('documents?select=*&company_id=eq.'+encodeURIComponent(company)+'&system_id=eq.'+encodeURIComponent(system)+'&order=created_at.desc');const folder=document.querySelector('.panel table');if(!folder)return;const rows=docs.filter(d=>{const txt=folder.closest('.panel')?.querySelector('h2')?.textContent||'';return true});const tbody=folder.querySelector('tbody');if(!tbody)return;const currentFolder=document.querySelector('.navitem.sel')?.getAttribute('data-folder');const currentSub=document.querySelector('.subitem.sel')?.getAttribute('data-sub');const visible=docs.filter(d=>(!currentFolder||d.folder_id===currentFolder)&&(!currentSub||d.subfolder_id===currentSub));tbody.innerHTML=visible.length?visible.map(d=>'<tr><td>'+esc(d.code)+'</td><td>'+esc(d.name)+'</td><td>'+esc(d.type)+'</td><td>'+esc(d.version)+'</td><td>'+esc(d.status)+'</td><td><span class="muted">Guardado</span></td></tr>').join(''):'<tr><td colspan="6" class="empty">No hay documentos en esta ubicación.</td></tr>';const stats=[...document.querySelectorAll('.stats>div')];if(stats[3]){const strong=stats[3].querySelector('strong');if(strong)strong.textContent=docs.length}document.querySelectorAll('.navitem').forEach(b=>{const id=b.getAttribute('data-folder');const n=docs.filter(d=>d.folder_id===id).length;const x=b.querySelector('b');if(x)x.textContent=n});document.querySelectorAll('.subitem').forEach(b=>{const id=b.getAttribute('data-sub');const n=docs.filter(d=>d.subfolder_id===id).length;const x=b.querySelector('b');if(x)x.textContent=n})}catch(e){console.warn('No se pudieron pintar documentos',e)}}
let timer=null;const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(paintDocuments,250)});observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',async()=>{await syncLocalDocuments();setTimeout(paintDocuments,1000)});
})();
