(()=>{'use strict';
const SB_URL='https://blonebsjvsborinfmyhg.supabase.co';
const SB_KEY='sb_publishable_RgvgvQDV9gnxZe-tin1vLA_i5P6jLVq';
const H={apikey:SB_KEY,Authorization:'Bearer '+SB_KEY};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opts={}){const r=await fetch(SB_URL+'/rest/v1/'+path,{...opts,headers:{...H,'Content-Type':'application/json',...(opts.headers||{})}});const t=await r.text();if(!r.ok)throw new Error('Supabase '+r.status+': '+t);return t?JSON.parse(t):null}
async function localRows(){return new Promise(resolve=>{try{const r=indexedDB.open('PC_LOCAL_V4');r.onsuccess=()=>{const db=r.result;if(!db.objectStoreNames.contains('documents'))return resolve([]);const q=db.transaction('documents').objectStore('documents').getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>resolve([])};r.onerror=()=>resolve([])}catch(e){resolve([])}})}
async function migrate(){try{const rows=await localRows();for(const d of rows){if(!d?.id||!d.companyId||!d.systemId||!d.folderId||!d.name)continue;const body={id:d.id,company_id:d.companyId,system_id:d.systemId,folder_id:d.folderId,subfolder_id:d.subfolderId||null,code:d.code||'',name:d.name,type:d.type||'ARCHIVO',version:d.version||'01',status:d.status||'BORRADOR',description:d.description||'',created_at:d.createdAt||new Date().toISOString(),updated_at:d.updatedAt||new Date().toISOString()};await api('documents',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)})}}catch(e){console.warn('Migracion de documentos locales:',e)}}
function pathOf(d){const s=String(d?.description||''),p='documentos-clientes/';const i=s.indexOf(p);return i>=0?s.slice(i+p.length):''}
async function openDoc(path,name){try{if(!path)return alert('Este documento no tiene un archivo asociado en Storage.');const r=await fetch(SB_URL+'/storage/v1/object/download/documentos-clientes/'+path,{headers:H});if(!r.ok)throw new Error(await r.text());const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';a.download=name||'documento';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}catch(e){alert('No se pudo abrir el archivo: '+e.message)}}
async function paint(){try{const company=document.querySelector('#company')?.value,system=document.querySelector('#system')?.value;if(!company||!system)return;const docs=await api('documents?select=*&company_id=eq.'+encodeURIComponent(company)+'&system_id=eq.'+encodeURIComponent(system)+'&order=created_at.desc');const folder=document.querySelector('.navitem.sel')?.dataset.folder||document.querySelector('.navitem[data-folder]')?.dataset.folder;const sub=document.querySelector('.subitem.sel')?.dataset.sub||'';const visible=docs.filter(d=>d.folder_id===folder&&(!sub||d.subfolder_id===sub));const table=document.querySelector('#content table'),tbody=table?.querySelector('tbody');if(!tbody)return;tbody.innerHTML=visible.length?visible.map(d=>'<tr><td>'+esc(d.code)+'</td><td>'+esc(d.name)+'</td><td>'+esc(d.type)+'</td><td>'+esc(d.version)+'</td><td>'+esc(d.status)+'</td><td><button class="btn" data-open-doc="'+esc(d.id)+'">Abrir</button></td></tr>').join(''):'<tr><td colspan="6" class="empty">No hay documentos aquí. Usa “Crear documento” o “Subir documento”.</td></tr>';const stat=document.querySelectorAll('.stats>div')[3]?.querySelector('strong');if(stat)stat.textContent=visible.length;document.querySelectorAll('.navitem').forEach(b=>{const x=b.querySelector('b');if(x)x.textContent=docs.filter(d=>d.folder_id===b.dataset.folder).length});document.querySelectorAll('.subitem').forEach(b=>{const x=b.querySelector('b');if(x)x.textContent=docs.filter(d=>d.subfolder_id===b.dataset.sub).length});table.querySelectorAll('[data-open-doc]').forEach(b=>b.onclick=()=>{const d=docs.find(x=>x.id===b.dataset.openDoc);openDoc(pathOf(d),d?.name)})}catch(e){console.warn('Visualizacion de documentos:',e)}}
async function refresh(){await migrate();for(let i=0;i<10;i++){await new Promise(r=>setTimeout(r,800));await paint()}}
window.addEventListener('load',refresh);setInterval(paint,2500);
})();
